# This demo assumes that AZ CLI and Terraform CLI have been installed
# and are accessible from the command line terminal on your machine

#1 initialize terraform in this directory
init:
    terraform init

#format a tf file
format:
    terraform fmt

#create a tf plan
plan:
    terraform plan

#create a tf plan with an output for tf automation
planout:
    terraform plan -out=tfplan

#create a tf plan that overrides the prefix variable
planoverride:
    terraform plan -var 'storage-account-name-prefix=jazz' -out=tfplan

#execute a tf file (will generate a new plan file)
apply:
    terraform apply

#execute a tf file that overrides prefix
applyoverride:
    terraform apply -var 'storage-account-name-prefix=jazz'
#or you could simply use the tfplan file where you overrode the variable

#execute a tf file with existing tfplan during automation
applyout:
    terraform apply tfplan

#execute a tf file without asking for approval
applyauto:
    terraform apply -auto-approve

#show the state file
show:
    terraform show

#enumerate the sources in the state file
statelist:
    terraform state list

#show details of a particular resource
showres:
    terraform state show data.azurerm_resource_group.demo-res-group
    terraform state show azurerm_storage_account.myfirstaccount